spring:
  profiles:
    include: secret
  application:
    name: eLearningBackend

  datasource:
    url: jdbc:mysql://43.201.111.220:3306/elearning?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&readOnly=false
    username: root
    password: gj1111

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: elearning0326@gmail.com # 앱 비밀번호 발급받은 google 계정
    password: yeocyrtaeyhblglt # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 3000  # 연결 타임아웃 설정 (예: 3000ms = 3초)
          timeout: 5000            # 읽기 타임아웃 설정 (예: 5000ms = 5초)
          writetimeout: 5000       # 쓰기 타임아웃 설정

reset:
  base-url: https://localhost:3000/auth/forgot-password/reset-password # 프론트의 비밀번호 재설정 페이지 도메인

email:
  auth-code-expiration-time: 180000  # 3분 (밀리초 단위)

# 네이버 메일 별도 설정
naver-mail:
  host: smtp.naver.com
  port: 465
  username: knh1721@naver.com
  password: RPPSPK9D13YL
  properties:
    mail:
      smtp:
        auth: true
        ssl:
          enable: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory

# Iamport (PortOne) 관련 설정 추가
iamport:
#  apiKey: channel-key-491f18fe-e98b-4a59-8ae0-b4f1fb635190     # Iamport REST API 키 (채널 키)
  apiKey: 1071808156831361
#  apiSecret: SU5JTElURV9UUklQTEVERVNfS0VZU1RS   # Iamport REST API 시크릿 (signKey)
  apiSecret: RVHf64jJyYhQq0rajK61ZJmFlJRyBUNljUafCrJFOs9w66uKvLjKgBU46Tc8vwbmUNIKYHdjVFVRmWbn
  mid: INIpayTest              # 가맹점 ID (예: INIpayTest, 운영 시 발급받은 상점 ID)
  returnUrl: https://abcdefgh.ngrok.io/api/payment/result  # 결제 결과 콜백 URL