spring:
  profiles:
    include: secret
  application:
    name: eLearningBackend

  datasource:
    url: jdbc:mysql://43.201.111.220:3306/elearning?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&readOnly=false
    username: root
    password: gj1111

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: elearning0326@gmail.com # 앱 비밀번호 발급받은 google 계정
    password: yeocyrtaeyhblglt # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 3000  # 연결 타임아웃 설정 (예: 3000ms = 3초)
          timeout: 5000            # 읽기 타임아웃 설정 (예: 5000ms = 5초)
          writetimeout: 5000       # 쓰기 타임아웃 설정

email:
  auth-code-expiration-time: 180000  # 3분 (밀리초 단위)

# 네이버 메일 별도 설정
naver-mail:
  host: smtp.naver.com
  port: 465
  username: knh1721@naver.com
  password: RPPSPK9D13YL
  properties:
    mail:
      smtp:
        auth: true
        ssl:
          enable: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory