server:
  address: 0.0.0.0
  port: 8080

spring:
  profiles:
    include: secret
  application:
    name: eLearningBackend

  datasource:
    url: jdbc:mysql://43.201.111.220:3306/elearning?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&readOnly=false
    username: root
    password: gj1111

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: elearning0326@gmail.com # 앱 비밀번호 발급받은 google 계정
    password: yeocyrtaeyhblglt # 발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 3000  # 연결 타임아웃 설정 (예: 3000ms = 3초)
          timeout: 5000            # 읽기 타임아웃 설정 (예: 5000ms = 5초)
          writetimeout: 5000       # 쓰기 타임아웃 설정

reset:
  base-url: http://localhost:3000/auth/forgot-password # 프론트의 비밀번호 재설정 페이지 도메인

email:
  auth-code-expiration-time: 180000  # 3분 (밀리초 단위)

# 네이버 메일 별도 설정
naver-mail:
  host: smtp.naver.com
  port: 465
  username: knh1721@naver.com
  password: RPPSPK9D13YL
  properties:
    mail:
      smtp:
        auth: true
        ssl:
          enable: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory

# Iamport (PortOne) 관련 설정 추가
iamport:
  apiKey: 1071808156831361  # Iamport REST API 키 (채널 키)
  apiSecret: RVHf64jJyYhQq0rajK61ZJmFlJRyBUNljUafCrJFOs9w66uKvLjKgBU46Tc8vwbmUNIKYHdjVFVRmWbn # Iamport REST API 시크릿 (signKey)
  mid: INIpayTest              # 가맹점 ID (예: INIpayTest, 운영 시 발급받은 상점 ID)
  returnUrl: https://abcdefgh.ngrok.io/api/payment/result  # 결제 결과 콜백 URL

frontend:
  url: http://localhost:3000

oauth:
  kakao:  # 카카오 OAuth 설정
    client-id: e3aecedb65b63e1fac9d777cd66fb3e1
    client-secret: ftICfRArx3LAj0GOLOO7jqOzyLiF7OwK
    redirect-uri: http://localhost:3000/auth/auth/kakao-callback
  google: # 구글 OAuth 설정
    client-id: 617172854156-b05pg0gp7ktjl08lcil6svh8bj87dnvl.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/auth/auth/google-callback
  github: # 깃허브 OAuth 설정
    client-id: Ov23lihKiKICvlydhVsj
    client-secret: bf755cae913574910ab166476bccaa9884399582
    redirect-uri: http://localhost:3000/auth/auth/github-callback

coolsms:
  api-key: NCSZWG45BBQAFWFV
  api-secret: UTFXT1NPIX07N21HGNWIL9RYPNOPKNBN


