spring:
  application:
    name: eLearningBackend

  datasource:
    url: jdbc:mysql://43.201.111.220:3306/elearning?useSSL=false&serverTimezone=UTC
    username: root
    password: gj1111

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
